apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashes-deployment
  labels:
    app: hashes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hashes
  template:
    metadata:
      labels:
        app: hashes
    spec:
      containers:
        - name: hashes
          image: cbiot/hashes:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: hashes-configmap
            - secretRef:
                name: hashes-secret
          readinessProbe:
            httpGet:
              path: /metrics
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 1
          livenessProbe:
            httpGet:
              path: /metrics
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 1
