version: '3.8'
services:
  app1:
    build: ./app
    ports:
      - "5001:5000"
  app2:
    build: ./app
    ports:
      - "5002:5000"
  loadbalancer:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - app1
      - app2
